title: Guna Sekhar Varma Sangaraju
logo: /assets/img/Sai3-modified.png
description: A dedicated Machine Learning enthusiast with experience in developing data-driven solutions using Python, Django, Flask, and ML frameworks, passionate about applying AI technologies to healthcare applications while consistently expanding expertise through research and practical implementation of neural networks and cloud services.
show_downloads: false
theme: jekyll-theme-minimal
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/gunasekharvarma/
  - name: Email
    url: mailto:gunasekhar.sangaraju@gmail.com
