title: Guna Sekhar Varma Sangaraju
logo: /assets/img/Sai3-modified.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/gunasekharvarma/
  - name: Email
    url: mailto:gunasekhar.sangaraju@gmail.com
