title: Guna Sekhar Varma Sangaraju
logo: /assets/img/Sai3-modified.png
description: Machine Learning enthusiast skilled in Python, Django, Flask, and ML frameworks, passionate about AI in healthcare, with hands-on experience in neural networks, cloud services, and continuous research-driven development
resume_link: https://drive.google.com/file/d/1bT9YFboCxKNAzoecWdr8JogGw4hGg8Ui/view?usp=drivesdk
theme: jekyll-theme-minimal

