title: Guna Sekhar Varma Sangaraju
logo: /assets/img/Sai3-modified.png
description: ML enthusiast applying AI in healthcare using Python, Django, neural networks, cloud, and ongoing research.
show_downloads: true
theme: jekyll-theme-minimal

