title: Guna Sekhar Varma Sangaraju
logo: /assets/img/Sai3-modified.png
description: Machine Learning enthusiast skilled in Python, Django, Flask, and ML frameworks, passionate about AI in healthcare, with hands-on experience in neural networks, cloud services, and continuous research-driven development.
show_downloads: true
theme: jekyll-theme-minimal

